name: Build MeshChat Package
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      build_dir:
        required: true
        type: string

jobs:
  create-meshchat-package:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/wt0f/gitlab-runner-images/shell:latest
    outputs:
      package_file: ${{ steps.detect-package-file.outputs.file }}
    steps:
      - uses: actions/checkout@v3
      - run: info "Populating the filesystem with MeshChat files"
      - run: package/populate-meshchat-fs.sh ${{ inputs.build_dir }}
      - run: info "Updating version numbers to "
      - run: package/update-version.sh ${{ inputs.build_dir }}
      - run: info "Packing up MeshChat files"
      - run: package/ipk-build.sh ${{ inputs.build_dir }}
      - id: detect-package-file
        run: echo "file=$(ls -1 meshchat_*.ipk)"
      - uses: actions/upload-artifact@v3
        with:
          name: meshchat
          path: |
            meshchat_*.ipk
            VERSION
